version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "packages/server-base-log/test"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "packages/server-base-log"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "packages/server-base"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "packages/server-base-router/test"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "packages/server-base-router"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "."
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
