from node:6.9-wheezy

maintainer James Kyburz "james.kyburz@gmail.com"

RUN apt-get update &&\
  apt-get install -y --force-yes --no-install-recommends\
  curl ssh &&\
  rm -rf /var/lib/apt/lists/*

RUN curl -o- -L https://yarnpkg.com/install.sh | bash
ENV PATH "$PATH:/root/.yarn/bin"

ONBUILD WORKDIR /usr/src/app
ONBUILD ADD yarn.lock package.json /usr/src/app/
ONBUILD RUN yarn install
ONBUILD ADD . /usr/src/app
ONBUILD CMD yarn start
