from node:6.6-wheezy

RUN apt-get update &&\
  apt-get install -y --force-yes --no-install-recommends\
  ssh &&\
  rm -rf /var/lib/apt/lists/*

ONBUILD RUN mkdir -p /usr/src/app
ONBUILD WORKDIR /usr/src/app
ONBUILD ADD . /usr/src/app
ONBUILD RUN npm install
ONBUILD CMD npm start
