name: ci

concurrency:
  group: ci
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: "14"
      - name: run tests
        run: |
          npm t
  automerge:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.7.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
